apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erp-backend.fullname" . }}
  labels:
    {{- include "erp-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "erp-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "erp-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "erp-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "erp-backend.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 44343
              protocol: TCP
          env:
            - name: POSTGRES_CONSTR
              valueFrom:
               secretKeyRef:
                name: erp-backend
                key: pg-connection-string
            - name: PERSISTENT_PATH
              value: "/app/JS_PERSISTENT_FILES_DIRECTORY/"
          volumeMounts:
          - name: {{ include "erp-backend.fullname" . }}
            mountPath: "/app/JS_PERSISTENT_FILES_DIRECTORY/"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "erp-backend.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ include "erp-backend.fullname" . }}
