{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "erp-backend.fullname" . }}
  labels:
    {{- include "erp-backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.ingress.domain }}
    #secretName:  {{ include "erp-backend.fullname" . }}-{{ .Values.ingress.domain | replace "." "-"}}
    secretName:  {{ include "erp-backend.fullname" . }}.{{ .Values.ingress.domain }}
  rules:
  - host: {{ .Release.Name }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "erp-backend.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
