{{- if .Values.persistentVolumeClaim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "erp-backend.fullname" . }}
  labels:
        {{- include "erp-backend.selectorLabels" . | nindent 8 }}
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessModes }}
  storageClassName: {{ .Values.persistentVolumeClaim.name }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.requests.storage }}
{{- end }}
