apiVersion: v1
kind: Service
metadata:
  name: {{ include "erp-backend.fullname" . }}
  labels:
    {{- include "erp-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "erp-backend.selectorLabels" . | nindent 4 }}
